#!/usr/bin/env bash

readonly archive_name=archive

clean() {
	rm -f css/*.min.css
	rm -fd css/
	rm -f js/*.min.js
	rm -fd js/
	rm $archive_name.zip
}

validate() {
	jslint src/js/*.js
}

compile_css() {
	local files=( main )
	mkdir css/
	for f in "${files[@]}"; do
		uglifycss src/css/$f.css > css/$f.min.css
	done
}

compile_js() {
	local files=( spin-the-choice )
	mkdir js/
	for f in "${files[@]}"; do
		uglifyjs src/js/$f.js -c -m -o js/$f.min.js
	done
}

build() {
	local name=archive
	zip $archive_name *.html
	zip $archive_name css/*.min.css
	zip $archive_name js/*.min.js
	zip $archive_name assets/image/*.*
	zip $archive_name assets/sound/*.*
}

clean
validate
compile_css
compile_js
build

